#!/usr/bin/env bash
# Configure /etc/hosts so localhost -> 127.0.0.2 and facebook.com -> 8.8.8.8

sudo sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2\tlocalhost/' /etc/hosts
if grep -q '[[:space:]]facebook\.com' /etc/hosts; then
  sudo sed -i 's/^[0-9.]\+[[:space:]]\+facebook\.com/8.8.8.8 facebook.com/' /etc/hosts
else
  echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts >/dev/null
fi

